FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/openjdk-21-runtime:1.17-2
MAINTAINER baeldung.com
COPY target/spring-boot-complete-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
